In [1]:
import numpy as np

my_array = np.array(5)
my_array


array(5)

In [7]:
my_array = np.arange(12)
matrix0 = my_array.reshape(3, 4)
matrix0


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
matrix1 = my_array.reshape(3, 2, 2)
matrix1

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [9]:
matrix1 = my_array.reshape(2, 2, 3)
matrix1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [13]:
print('shape: ' + str(matrix1.shape) + '\ndim: ' + str(matrix1.ndim) +
      '\nsiz3: ' + str(matrix1.size) + '\ntype: ' + str(matrix1.dtype))

shape: (3, 2, 2)
dim: 3
siz3: 12
type: int32


In [18]:
zeros_matrix = np.zeros((1, 3))
zeros_matrix

array([[0., 0., 0.]])

In [17]:
ones_matrix = np.ones((3, 1))
ones_matrix

array([[1.],
       [1.],
       [1.]])

In [22]:
print(ones_matrix * zeros_matrix)
print()
print(zeros_matrix * ones_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
a = np.array([10, 20, 30])
b = np.array(3)
a - b


array([ 7, 17, 27])

In [24]:
a < 20


array([ True, False, False])

In [25]:
np.random.rand(3, 4)

array([[0.15387671, 0.48980248, 0.07758444, 0.34055992],
       [0.28353788, 0.96079186, 0.51968047, 0.35121975],
       [0.80406148, 0.50950233, 0.04666402, 0.40813839]])

In [27]:
np.random.randn(10 , 10)

array([[-0.88429833,  0.93644164, -0.74678501, -0.50883157,  0.75152072,
         0.72363298, -0.55507174,  0.0498601 ,  1.47526237, -0.32524785],
       [ 2.66654593, -0.86576344,  1.41019083,  1.22823867, -0.89688456,
        -1.82944697,  0.43544908,  0.12572374, -1.14668956, -0.11767779],
       [ 0.87688905,  1.08983487, -0.49876458, -0.01569867, -0.14629484,
        -0.30153981,  1.23798665, -1.83080147,  0.39267949, -1.1058653 ],
       [ 0.09009967,  0.05673727, -0.8859144 , -0.48939623,  0.15145365,
        -0.2082311 ,  0.47384219, -0.73626357, -0.05126657,  0.04458665],
       [-2.12824883,  1.27726235,  0.05758556, -1.09753993,  0.7553957 ,
         0.69280771,  0.17737378,  0.97441026,  0.21324094,  0.79448823],
       [-2.54156956, -0.57682072, -0.84077666, -0.93987499, -1.31091574,
        -0.34830057, -0.00990587,  2.44391364, -0.50632515,  0.12683191],
       [-0.86988838,  0.89202746, -0.35281504,  1.67165616, -1.39523961,
        -0.76736153,  0.29500302,  0.05235149

In [29]:
np.random.randint(2, 10)

3

In [30]:
np.nan

nan