In [1]:
import numpy as np

my_array = np.array(5)
my_array


array(5)

In [7]:
my_array = np.arange(12)
matrix0 = my_array.reshape(3, 4)
matrix0


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
matrix1 = my_array.reshape(3, 2, 2)
matrix1

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [9]:
matrix1 = my_array.reshape(2, 2, 3)
matrix1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [13]:
print('shape: ' + str(matrix1.shape) + '\ndim: ' + str(matrix1.ndim) +
      '\nsiz3: ' + str(matrix1.size) + '\ntype: ' + str(matrix1.dtype))

shape: (3, 2, 2)
dim: 3
siz3: 12
type: int32


In [18]:
zeros_matrix = np.zeros((1, 3))
zeros_matrix

array([[0., 0., 0.]])

In [17]:
ones_matrix = np.ones((3, 1))
ones_matrix

array([[1.],
       [1.],
       [1.]])

In [22]:
print(ones_matrix * zeros_matrix)
print()
print(zeros_matrix * ones_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
a = np.array([10, 20, 30])
b = np.array(3)
a - b


array([ 7, 17, 27])

In [24]:
a < 20


array([ True, False, False])